spring:
  application:
    name: waimai-order-sys
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#    publisher-returns: true
#    publisher-confirms: true
#    template:
#      mandatory: true
  datasource:
    username: root
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/waimai?useSSL=false&serverTimezone=UTC
    password: 1234
server:
  port: 7002
mybatis:
  mapper-locations: classpath:/mapper/*.xml